### ISSUE TITLE
what's the strategy of this book?

### ISSUE THREAD

**Issue by snowden-fu** [niudai/Spring-Boot-Learning-Book#1]
I am just wondering whether the book include Spring basics or just for Spring Boot for senior learners?

**Comment by niudai** [comment]
The book would include Spring Framework basics such as Dependency Injection, IoC Container, Beans, etc, by which beginers can start off quickly with this book.
The prequisite for this book should be Java basic and Maven basic.



---Original---

**Comment by snowden-fu** [comment]
okay, so I propose that some difficult conceptions like DI, AOP, should be interpreted as simple as possible, so that the book is friendly to all readers.
