### ISSUE TITLE
Maven may not be a good prerequisite

### ISSUE THREAD

**Issue by snowden-fu** [niudai/Spring-Boot-Learning-Book#3]
I don't think Maven is a good prerequisite for all learners. For instance, most people who 's majoring CS or relative subjects never use Maven if just taking courses without any project practice.

so I propose that Maven should be mentioned and simply introduced in some chapters

**Comment by Lunaticf** [comment]
Maybe as you said. But to learn spring really needs to be familiar with the Java foundation. If you are familiar with Java, it is hard to imagine that you have not touched the package management tool. Maven is a unique tool, but package management tools are a more general concept in programming and should be familiar to most people or CS Students. A brief introduction to the package management tool in programming and then introduct Maven  is also a good choice.

**Comment by niudai** [comment]
I would open a new section to give a brief introduction and usage of maven. It's true that package management tool is a basic concept everyone should know, so we would introduce this concept in maven section. Thanks for advice.
